name: Deploy
on:
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    environment: turkey
    steps:
    - name: Deploy stub
      run: |
        echo "Placeholder for deployments"

